# https://www.mkdocs.org/user-guide/deploying-your-docs/

site_name: jaimesendraberenguer
site_url: https://jaisenbe58r.github.io/jaimesendraberenguer/
site_author: Jaime Sendra Berenguer
site_description: A library consisting of useful tools and extensions for the day-to-day data science tasks.


repo_url: https://github.com/jaisenbe58r/jaimesendraberenguer
repo_name: GitHub
edit_uri: docs/

theme:
    name: null
    custom_dir: 'custom_theme/'

markdown_extensions:
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True #for use of inline $..$
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - cinder/css/base.css
  - cinder/css/bootstrap-custom.css
  - cinder/css/bootstrap-custom.min.css
  - cinder/css/cinder.css
  - cinder/css/font-awesome-4.0.3.css
  - cinder/css/highlight.css

copyright: Copyright &copy; 2018-2022 <a href="https://www.linkedin.com/in/jaisenbe">Jaime Sendra</a>


nav:
- Home: index.md
- Portfolio:
  - 02_Portfolio\example.md
- Blog:
  - 01_Blog\01_Pipeline_NN\doc\Pipeline_para_el_entrenamiento_de_Redes_Neuronales.md
  - 01_Blog\02_AI_Industria\doc\AI_Industria.md
- About:
  - about.md
  - license.md
  


# - Installation: installation.md
# - About:
#   - Release Notes: CHANGELOG.md
#   - How To Contribute: CONTRIBUTING.md
#   - Contributors: contributors.md
#   - License: license.md
#   - Citing mlearner: cite.md
#   - Discuss: discuss.md
